### PR TITLE
ru_RU.lang update

### PR DESCRIPTION
**Pull request by kraineff**

### CODE REVIEW

**Comment by labpaw** [comment]
No. I might change slime block translation, nothing else.

**Comment by buttilda** [comment]
Can't you just look at the "official" translation for those blocks and use that? :P

**Comment by kraineff** [comment]
I add "official" translate!

**Comment by kraineff** [comment]
oops

**Comment by kraineff** [comment]
И да @Adaptivity то зелье правильнее "Длительное", но не как ни "Стелющееся"

**Comment by labpaw** [comment]
Official translations aren't really ready. They are in-progress and will be changed a lot of times. For now I won't change anything since my translations are better. Official Minecraft localization is a piece of shit. Mojang don't really care about translations.
@TheVizzy you can change potion localization and slime block localization. For the rest - no.

**Comment by kraineff** [comment]
@Adaptivity Do you think it's normal not allow to translate modes? And to do all in one. And ignore the other translates. (Like they are worse than your, in your own opinion)

**Comment by kraineff** [comment]
I think my translation better

**Comment by labpaw** [comment]
Yes, it's normal. I'm making translations for 3 years for free. My language skills waaay better than yours. So, I know better which translation is better. Want to change something what I declined? Use resource pack.

**Comment by kraineff** [comment]
Haha. GitHub is created so that people have modified projects and not one person. I do not say anything about you translate. But do not change them, it is too. Especially since you're not a author of mod and not for you to decide, which translate better.

**Comment by kraineff** [comment]
Let independent person decides which translation rows which I changed the better. if smth.

**Comment by kraineff** [comment]
And your 3 years not speak about nothing. Everyone can make mistakes. I just changed a couple of lines, and you're already talking about that nonsense.

**Comment by labpaw** [comment]
But there are no mistakes in this translation... You just changed block names... Anyway, yes, I can't stop from changing this, so if this gets accepted, I'll move current translation to my resource pack and stop updating this one, so you can do whatever you want.

**Comment by kraineff** [comment]
All right. "Фиолетовый блок" not so-called exact!

**Comment by kraineff** [comment]
In short I do not care. Decide what you want. I'm tired of the negativity on my translate. I go translate another mods.

**Comment by labpaw** [comment]
Fine. I can change this too.

**Comment by kraineff** [comment]
Nice job @Adaptivity

**Comment by buttilda** [comment]
Should I merge both the PRs or just @Adaptivity's one?

**Comment by labpaw** [comment]
Only my.

**Pull request closed without merging**
