### PR TITLE
Fix Brewing Stand CME trying replace several times in a row.

### PR DESCRIPTION
**Pull request by mrammy**
I was going to fix the brewing stand icon to make it grab whatever the vanilla icon was rather then just the top icon too, but I got kind of lazy. Settled for just adding a localization so the name doesn't look ugly. This PR should fix the CME you get while trying to replace brewing stands in the world. Not really sure how performance taxing this is to run all the time but meh.

### CODE REVIEW

**Comment by buttilda** [comment]
But you shouldn't be getting CMEs with that because I return after I remove the first brewing stand. So only one is replaced per tick.

**Comment by buttilda** [comment]
Thanks for the localisation though, forgot about that :3

**Comment by mrammy** [comment]
Try it with fastcraft.

**Comment by mrammy** [comment]
ugh and it still happens I guess it has to do with how loadedTileEntityList is being modified. At the same time it's looping through it.

**Comment by buttilda** [comment]
I'll try with fastcraft.
I have a better idea on how to fix it though. wait up :3

**Comment by buttilda** [comment]
Loading a world with only Fastcraft and Et Futurum and placed down a bunch of Brewing Stands... no CME.

**Comment by mrammy** [comment]
It seemed to only act up on a dedicated server with fastcraft-1.22ctest17.jar not fastcraft-1.21.jar

**Comment by buttilda** [comment]
I tested with fastcraft-1.21.jar

**Comment by mrammy** [comment]
Well could just be fastcraft weirdness, I'll close and delete this if you don't think it's needed otherwise I'll keep testing

**Comment by buttilda** [comment]
I've just pushed a change so that the brewing stands get replaced after the world ticked instead of before. Might stop the crash. Would you mind testing it? I would test myself but, as I've explained, the crash isn't happening on my system.

**Comment by buttilda** [comment]
Also, where did you get that version of fastcraft? On the website I'm looking at the only one available is 1.21.

**Comment by mrammy** [comment]
http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820&pageNo=55&s=5b81fdd4fd547674811bdf397b74c0f321675129

**Comment by buttilda** [comment]
Thanks. I'll try it with that version.

**Comment by buttilda** [comment]
Tried it with that version. No crash.
Maybe it's a third mod?

**Comment by mrammy** [comment]
The fix you posted earlier worked for a little while and then threw the same CME I keep encountering

http://hastebin.com/iduhupiwix.avrasm guess it could be any of these misbehaving and your mods is just getting the short end of the stick so to speak, and getting blamed for it. 

Sorry for the confusion, but additionally my line 31 in that log is equivalent to your [line 25](https://github.com/ganymedes01/Et-Futurum/blob/master/src/main/java/ganymedes01/etfuturum/core/handlers/WorldTickEventHandler.java#L25). Just merged your changes and commented out all that crap I did trying to fix the thing that doesnt want to cooperate.

**Comment by buttilda** [comment]
If you load a new super-flat world and don't put any brewing stands down, does the crash still happen randomly?

I'm starting to think that fastcraft is the one modifying the list somewhere else while I'm trying to iterate on it.

**Comment by mrammy** [comment]
Yep flatworld crashes instantly. I just updated java so I'm going to see if that helps for whatever reason. Are you using java 8 or java 7? Just covering all the bases.

**Comment by buttilda** [comment]
Java 8.
I noticed you have a lot of mods that also do stuff in the WorldTickEvent, maybe it's one of them?

**Comment by buttilda** [comment]
Why did you close this? Did you find out what the problem was?

**Comment by mrammy** [comment]
Yes. NotEnoughIDs and fastcraft weirdness that simply made it seem like it was your mods fault.

**Comment by buttilda** [comment]
Ah okay :3
Well let me know if you find any other issues, I appreciate the help :)

**Comment by mrammy** [comment]
Or "features" you never know ;)

**Comment by buttilda** [comment]
I'd appreciate that too ;D

**Comment by mrammy** [comment]
this is still bothering me and I'm trying to track it down. It's not actually fastcraft is has to do with the fact that the loadedTileEntityList isn't a thread safe implementation. So if anything else tries to access it while your accessing it, it will crash. Which could be any mod that needs to use that list. A safer way of running this would be to use ASM to replace the vanilla brewing block in it's update event exclusively for that tile entity. The performance impact on a large server of having to loop through this list no matter how often you do it is probably not worth the upsides of how simple the current method is.

**Pull request closed without merging**
